### ISSUE TITLE
[QUESTION]: [karavi-observability-1.8.0]: PowerScale read privilege is required: Statistics (ISI_PRIV_STATISTICS)

### ISSUE THREAD

**Issue by ybrock** [dell/helm-charts#408] opened 2024-04-09 14:14 UTC
Hello,

We have setup karavi-observability with the helm chart.

It's working quite good : metrics are collected through otel, karavi-metrics and karavi-topology.

We have set the correct permissions "Statistics" to "Read" for the user we use to connect to the PowerScale array, but : 
* we see messages like this this in the karavi-metrics-powerscale pod : 
```
[ERROR] Error in response. Method:GET URI:platform/3/statistics Error: Privilege check failed. 
The following read privilege is required: Statistics (ISI_PRIV_STATISTICS) JSON Error: Privilege check failed. 
The following read privilege is required: Statistics (ISI_PRIV_STATISTICS)

```

* from time to time the metrics are not collected anymore and we have to restart karavi-metrics-powerscale pod

Have you seen this beforfe ?

Kind regards

**Comment by donatwork** [comment] 2024-06-14 01:39
Hello, the error is coming from the array. You probably already know that. Are you sure that you have the correct access permissions set for the user you have configured for the driver and Observability? We have not see that error. If you can report the actual access permissions that are used we can take a look. What version of PowerScale is being used? Is Authorization also used?

**Comment by ybrock** [comment] 2024-06-14 07:07
Hello,

Thank you for your input.

We've reviewed the permissions with our PowerScale admin team many times ; it seems the required permissions are set.

```
Privileges
ISI_PRIV_LOGIN_PAPI (Read only)
ISI_PRIV_AUTH (Read only)
ISI_PRIV_NFS (Read write)
ISI_PRIV_QUOTA (Read write)
ISI_PRIV_SNAPSHOT (Read write)
ISI_PRIV_STATISTICS (Read only)
ISI_PRIV_SYNCIQ (Read write)
ISI_PRIV_IFS_BACKUP (Read only)
ISI_PRIV_IFS_RESTORE (Read only)
ISI_PRIV_NS_IFS_ACCESS (Read only)
```

The PowerScale is running OneFS Version: 9.5.0.8

We're not using the Authorization CSM module

Kind regards

**Comment by donatwork** [comment] 2024-06-14 10:07
You mentioned that "from time to time the metrics are not collected anymore", does it mean that metrics are collected at some times then eventually stop? When the problem starts then a good test is to manually use a tool, e.g. curl to make the REST API request and see if the problem exists outside of the pod. That can further isolate where the issue is.

If it turns out that the REST call succeeds outside of the pod then perhaps there could be a problem in the pod. Some logs of the pods (driver, observability, metrics) operation would be needed.

**Comment by ybrock** [comment] 2024-06-14 14:09
The problem with collecting the metrics is no more. After upgrading the CSM modules to 1.31 we did not get this issue and the metrics are always reported.
There is only this message in the log :

`[ERROR] Error in response. Method:GET URI:platform/3/statistics Error: Privilege check failed. 
The following read privilege is required: Statistics (ISI_PRIV_STATISTICS) JSON Error: Privilege check failed. 
The following read privilege is required: Statistics (ISI_PRIV_STATISTICS)
`

Maybe there is some verbosity/debug to activate to get more infos.
I will see if I can get more details

**Comment by shaynafinocchiaro** [comment] 2024-06-26 12:39
Closing out this issue as resolved. Please feel free to open another issue if the problem occurs again. If you don't get a timely response in this repository, github issues can be filed [here ](https://github.com/dell/csm/issues) as well. Thank you.

**Closed by shaynafinocchiaro** 2024-06-26 12:39 UTC
Labels: type/question
